### ISSUE TITLE
Failed to ensure android components, error: output: Starting a Gradle Daemon, 1 busy Daemon could not be reused

### ISSUE THREAD

**Issue by tir38** [bitrise-steplib/steps-install-missing-android-tools#38]
Using v 2.2.0 of this step I get the following error randomly:

```
Failed to ensure android components, error: output: Starting a Gradle Daemon, 1 busy Daemon could not be reused, use --status for details
```

If I close the PR this is built against and re-open (i.e. trick BR into rebuilding w/out cache) then everything works fine.

**Comment by BirmacherAkos** [comment]
Hi @tir38 !

Could you try running your build on the Android & Docker, on Ubuntu 16.04 - LTS Stack stack?

We got reports of an issue with gradle on the 18.04 stack that we are still investigating. Which version of gradle are you using?

**Comment by tir38** [comment]
Sure i'll try 16.04 and report back.

We are using Gradle 4.4 and AGP 3.1.1

**Comment by viktorbenei** [comment]
@saschoar are you sure that you have the same issue, the `Starting a Gradle Daemon, 1 busy Daemon could not be reused` one? Can you copy paste the related build's bitrise.io URL?

**Comment by saschoar** [comment]
@viktorbenei Yep, we noticed it here: https://app.bitrise.io/build/64bb21679ac60dfa and here: https://app.bitrise.io/build/ca14d2c2bb74cb05

**Comment by viktorbenei** [comment]
Thanks @saschoar  - we could reproduce this as well in the meantime. For some reason Gradle on Ubuntu 18 (using the official Ubuntu 18 docker image / environment) has encoding issues and crashes for any non ASCII character in env vars, which includes emojis.

We're still working on the fix, in the meantime please use the LTS stack which uses Ubuntu 16 instead of Ubuntu 18.

**Comment by tir38** [comment]
LOL. this might match up to our experience too. I never would have put it together.
