### ISSUE TITLE
Unknown field 'ForceAttemptHTTP2' in struct literal of type http.Transport with v2.3.9 when running on Android & Docker on Ubuntu 16.04 - LTS Stack 

### ISSUE THREAD

**Issue by anthonymonori** [bitrise-steplib/steps-install-missing-android-tools#76]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? **2.3.9**
- Is the issue reproducible with the latest version? **YES**
- Does the issue happen sporadically, or every time? **EVERY TIME**
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? **NO**

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

Since 2.3.9 was released, we started seeing all of our builds failing with the following error message:
```
| (6) install-missing-android-tools                                            |
+------------------------------------------------------------------------------+
| id: install-missing-android-tools                                            |
| version: 2.3.9                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2021-06-24T16:04:45Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
# github.com/bitrise-steplib/steps-install-missing-android-tools/vendor/github.com/hashicorp/go-cleanhttp
src/github.com/bitrise-steplib/steps-install-missing-android-tools/vendor/github.com/hashicorp/go-cleanhttp/cleanhttp.go:35:3: unknown field 'ForceAttemptHTTP2' in struct literal of type http.Transport
ERRO[16:04:46] Step (install-missing-android-tools) failed: Failed to prepare the step for execution through the required toolkit (go), error: Failed to install package, error: exit status 2 
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | install-missing-android-tools (exit code: 1)                  | 1.65 sec |
+---+---------------------------------------------------------------+----------+
| Issue tracker: ...bitrise-steplib/steps-install-missing-android-tools/issues |
| Source: ...://github.com/bitrise-steplib/steps-install-missing-android-tools |
```

Seems to be related to the Android & Docker on Ubuntu 16.04 - LTS Stack since I cannot reproduce this locally.

The timeline matches the release and only seeing this error on workflows running the 2.3.9 version of the above step.

### Steps to reproduce

1. Running on Android & Docker on Ubuntu 16.04 - LTS Stack
2. Use install-missing-android-tools@2.3.9
3. See it fail constantly with the above mentioned error

Related to https://github.com/bitrise-io/bitrise-steplib/pull/3084 ?

**Comment by mateherber** [comment]
Hi @anthonymonori,

Thanks for reporting this issue. Probably the fail is related to the latest release and the root cause is the ancient go version of the LTS stack. For now, you can either use the previous version of the step or update the stack to the supported ubuntu (20.04).

Out of curiosity, is there something that prevents you from updating to the latest ubuntu or just happened to stay on that LTS stack?

**Comment by anthonymonori** [comment]
Thanks! Indeed not a blocker, -- for now we downgraded to 2.3.8.

Regarding why we are on the legacy stack -- the deprecation doesn't seem obvious (to me at least; I only know about it since I checked it and spotted in the name of the stack). It's still a bit unsure what would it entail if we don't upgrade before the time mentioned there. Other than that, I don't see in any blocker in upgrading. One concern I have is that there's no easy way to test such upgrade, and (from what I can tell) once I select the new stack and apply, the old one won't be selectable anymore leaving us in a potentially broken state.

Probably some more straight forward comms would help on the UI directly.

Thanks for looking into the issue! 🙂

**Comment by mateherber** [comment]
Thanks, I'll definitely bring this feedback to the team. Fair enough it is not really a great idea to push customers to update the stack but prevent them from going back if that fails. One thing that would work is to clone your workflow and set up the new stack for it. Test with that and if everything passes you can safely update the original.

Tomorrow we'll look into the issue.

**Comment by mateherber** [comment]
Hi @anthonymonori,

Sorry I didn't get back to you on this one. This (and many other) issue is present because the steps are targeting `golang` version `1.16` but this stack has an older version installed. At this point, our team doesn't have the intention to update `golang` version on the deprecated stack which leaves us with a few options if you're still experiencing this issue.

* Stay on the `2.3.8` version of the step if it works for your use-case
* Add a script step at the beginning of the workflow where you force update `golang` version to `1.16` or later
* Migrate to the supported Ubuntu 20.04 stacks

As the 16.04 is closing on its end-of-life date soon, I'd suggest moving your workflows to that stack which hopefully would render this issue obsolete.

**Comment by anthonymonori** [comment]
Thanks for looking into it and for providing some workarounds! We'll probably move off the Ubuntu 16.04 stack anyways, but hope it was helpful for others to see as well in case they have encountered the same issue!

Cheers!
